### ISSUE TITLE
run fail

### ISSUE THREAD

**Issue by mimsadAlef** [danopia/php-ircd#9]
hello
I have a problem executing the code
When I log in to the server with an IRC client, the server gives this error :(
```
Running...new user >>> :locahost NOTICE AUTH :*** Looking up your hostname...
new user >>> :locahost NOTICE AUTH :*** Found your hostname
PHP Warning:  spl_object_id() expects parameter 1 to be object, resource given in /tmp/php-ircd/connection_handler.php on line 48
 <<< NICK mimsadalef
PHP Fatal error:  Uncaught Error: Call to undefined function str_contains() in /tmp/php-ircd/connection_handler.php:63
Stack trace:
#0 /tmp/php-ircd/server.php(174): require()
#1 {main}
  thrown in /tmp/php-ircd/connection_handler.php on line 63
```

**Comment by danopia** [comment]
Hi,

To address #6 a user updated the code in this repo (#8) and now PHP 8 is required.

If you're using an earlier PHP you could try an older tree such as https://github.com/danopia/php-ircd/tree/e9cbb9a6ed84451db725916bf46103b610729d26.

Also, I do not support this code, I wrote it a long time ago.

Cheers
